from enum import Enum


class DutState(str, Enum):
    STARTUP = "STARTUP"
    NORMAL = "NORMAL"
    DERATE = "DERATE"
    FAULT = "FAULT"
    RECOVERY = "RECOVERY"


class FaultReason(str, Enum):
    NONE = "NONE"
    OVERVOLTAGE = "OVERVOLTAGE"
    OVERCURRENT = "OVERCURRENT"
    OVERTEMPERATURE = "OVERTEMPERATURE"
    SENSOR_TIMEOUT = "SENSOR_TIMEOUT"
    DATA_INTEGRITY = "DATA_INTEGRITY"
    STALE_SEQUENCE = "STALE_SEQUENCE"
    IMPLAUSIBLE_SLEW = "IMPLAUSIBLE_SLEW"
