REQUIREMENTS: dict[str, str] = {
    "SYS-001": "DUT shall enter a defined safe state after reset.",
    "COM-001": "DUT shall accept valid sensor frames at the specified update period.",
    "COM-002": "DUT shall reject frames with invalid checksum/CRC.",
    "COM-003": "DUT shall detect stale or missing sensor data within the specified timeout.",
    "COM-004": "DUT shall detect invalid or repeated sequence numbers according to the protocol rule.",
    "MON-001": "DUT shall maintain bus-voltage supervision.",
    "MON-002": "DUT shall maintain load-current supervision.",
    "MON-003": "DUT shall maintain temperature supervision.",
    "CTRL-001": "DUT shall assert ENABLE only when operating conditions are valid.",
    "CTRL-002": "DUT shall increase cooling/derating command as temperature/load severity increases.",
    "FLT-001": "DUT shall enter FAULT for defined severe electrical/thermal faults.",
    "FLT-002": "DUT shall fail safe on sensor timeout and repeated integrity failure.",
    "FLT-003": "DUT shall reject physically implausible sensor behavior where implemented.",
    "REC-001": "DUT shall not recover until healthy conditions persist for the specified dwell time.",
    "DIAG-001": "DUT shall publish machine-readable diagnostic state and fault reason.",
    "TEST-001": "Automated framework shall save a pass/fail record for every executed test.",
    "TEST-002": "Every safety/control requirement shall map to at least one verification test.",
    "TEST-003": "Framework shall preserve raw evidence sufficient to reproduce or diagnose a failure.",
}
